### ISSUE TITLE
References issue

### ISSUE THREAD

**Issue by AStupidBear** [jfbercher/jupyter_latex_envs#11]
(<a id="cit-gerstner2014neuronal" href="#call-gerstner2014neuronal">Gerstner, 2014</a>) Wulfram Gerstner, ``_Neuronal dynamics : from single neurons to networks and models of cognition_'',  2014.

I thin the last line should be "..." not ``..."

**Comment by jfbercher** [comment]
Hi, these kind of quotes will render correctly in LaTeX as "typographic quotes" instead of typewriter/straight quotes. See the wikipedia [article](https://en.wikipedia.org/wiki/Quotation_mark) on quotes. anyway, if you want change this (eg because it looks better on the html output), you can edit the citation templates available in the top of the file `latex_env.js`. Thanks for using this extension. I am always happy to know that it is useful for people!
