### ISSUE TITLE
Some improvements have been done by me.

### ISSUE THREAD

**Issue by shanhaiying** [jfbercher/jupyter_latex_envs#2]
@jfbercher , thanks for your work about latex_envs.  I begin typesetting something using it in sagemath's jupyter notebook about two months ago.  During this period, I add some codes into latex_envs for meeting my requirements. For example, changing the style of theorems, adding suport for latex commands such \hspace, \vspace in text mode. 
See the following screenshot:

![image](https://cloud.githubusercontent.com/assets/1595652/18225908/96911d84-7231-11e6-9aaa-8740e95f8e17.png)

[files.zip](https://github.com/jfbercher/jupyter_latex_envs/files/453453/files.zip)

**Comment by jfbercher** [comment]
Thanks for sharing. I just had a look and there are certainly good ideas. 
I see that you added support for more numberings/counters, perhaps should we think of a way for adding some kind of styles for the users ? Actually, at the beginning I just wanted something to enable a quick copy and paste some my old latex in the notebook... This has grown.
Support for \vspace, etc in text mode is interesting. 
Do you want to pull request it in the main source? 

I will look further into your modifications. Thanks.

**Comment by shanhaiying** [comment]
@jfbercher , thmsInNb4.js in [files.zip](https://github.com/jfbercher/jupyter_latex_envs/files/453453/files.zip)
includes some codes about the reference of theorem and \hspace.
![image](https://cloud.githubusercontent.com/assets/1595652/18229432/f03ac6b2-72ab-11e6-9e73-69d81d2b5c49.png)

 I  also make theorem environments accept optional parameter as theorem's title.

**Comment by jfbercher** [comment]
- I have integrated spacings (\hspace and \vspace)
- I saw the proposal for numbering nested enumerates, and integrated the `latex_list` class ; however I do not like so much the corresponding style, so I let it to be fixed by users. Perhaps will I add the loading of a user css that could be used to overwrite defaults styles. 
- I also saw that you suppressed the anchor corresponding to labels. this is legitimate; I will add a system parameter to  hide/display it. 
- Right, it could be interesting to show the number of the environment instead of its label when referencing to it, as you did. I will try to incorporate this in all generality -- which suppose reworking labels within environments. 
- ok for adopting your style for theorems and like, and use an optional parameter for the title. Will dig further this. 
- I need also to think on the way to number things within sections, perhaps with a connection with the toc2 extension; and let user choose a stytle of numbering... This will take some time. 

Thanks a lot

**Comment by shanhaiying** [comment]
Some problem about enumerating of sections and theorems:
If I put \section{...}  and \begin{thm} ...\end{thm} in the different markdown cells, it produces the results that I expected. 

![image](https://cloud.githubusercontent.com/assets/1595652/18280833/2cfec16a-748d-11e6-9dba-5ef132054f4d.png)

When I put them in the same markdown cell, the theorem is enumerate incorrectly. The counter of section is not increased after \section{...} being loaded. 

![image](https://cloud.githubusercontent.com/assets/1595652/18281069/02e04ea2-748e-11e6-938b-f2aea9b0e869.png)

**Comment by jfbercher** [comment]
This occurs in _your_ fork. As I far as I see, you should move the treatement of sections number _before_ replacing the envs, that is before the line `text = envReplace(text)`.
