### ISSUE TITLE
What happen while I convert the ipynb file to html?

### ISSUE THREAD

**Issue by shanhaiying** [jfbercher/jupyter_latex_envs#5]
I want to convert my ipnb files to html file for sharing them to others? 
According to the manual, I run the following command:
jupyter nbconvert --to html_with_lenvs chap1.ipynb

An error is reported. 

![image](https://cloud.githubusercontent.com/assets/1595652/18296952/ce515012-74df-11e6-811a-ca2e802a0720.png)

How to solve it?

**Comment by jfbercher** [comment]
I think that this a SageMath related issue. Try to install another python 3/jupyter installation, eg in a virtualenv and do the conversion with it. 

Also realize that since you have modified the source and css, the converted file will not include your modification since under the hood it runs the original javascript/css on the github CDN.

**Comment by shanhaiying** [comment]
I think that this is not an issue of SageMath.  According to [issues 362](https://github.com/jupyter/nbconvert/issues/362) of nbconvert, 
[Fix import from JSON in Python 2.7](https://github.com/ipython/ipython_genutils/pull/8/commits/3d47e88a02aafd49d88ee33eb96cfbdfc598b20b), 
I can obtain the html output.
As you say, the html file can't display theorems correctly since it runs online thmsInNb4.js. 
But about a month ago,  I've successfully convert the ipynb file to html file correctly. 
I check the html file and find that it run latex_envs by the following codes:

```
<!-- Custom stylesheet, it must be in the same directory as the html file -->
<link rel="stylesheet" href="custom.css"> 
<link rel="stylesheet" href="latex_envs.css"> 
```

**Comment by jfbercher** [comment]
I haven't enough information to find what can happens in the reported issue for
`jupyter nbconvert --to html_with_lenvs chap1.ipynb`
It works for me on linux/python3 and windows/python3. Do you have copied all the error message?

**Comment by shanhaiying** [comment]
Now jupyter do not report any error message. Then Terminal output as follows:

```
$ jupyter nbconvert --to html_with_lenvs chap0.ipynb

[NbConvertApp] Converting notebook chap0.ipynb to html_with_lenvs
[NbConvertApp] Support files will be in chap0_files/
[NbConvertApp] Making directory chap0_files
[NbConvertApp] Making directory chap0_files
[NbConvertApp] Making directory chap0_files
[NbConvertApp] Making directory chap0_files
[NbConvertApp] Making directory chap0_files
[NbConvertApp] Making directory chap0_files
[NbConvertApp] Writing 291215 bytes to chap0.html
```

But the latex environments uch as exam  in html file scan not be shown correctly.
![image](https://cloud.githubusercontent.com/assets/1595652/18315558/073a1df4-754a-11e6-9442-a5065bf4c19e.png)

**Comment by shanhaiying** [comment]
The problem have been solved by modifying  the file latex_envs.tpl such that nbconvert can usemy js/css file.

**Comment by shanhaiying** [comment]
When I convert the ipynb file to latex, the thm environments with optional argument are  converted into the following form:

```
    \begin{thm!cl{[}加法原理{]} \par
\begin{enumerate} \item 设\(S\) 是有限集， \item
\(S_i\subseteq S (i=1,2,\cdots, k)\), \item \(S=\bigcup_{i=1}^k S_i\),
\item \(S_i\bigcap S_j=\emptyset (1\leq i<j\leq k),\)
\end{enumerate} 则 \[\vert S \vert=\sum_{i=1}^k |S_i|\]

注意:划分的一个部分可以是空的, 但考虑一个或多个空部分的划分没有什么益处.
\end{thm}
```

What I should to do to solve it?

**Comment by jfbercher** [comment]
-  First reported issue was not specific to this extension. 
- The second one was due to the fact that you have added some environments in the source. These are not included/supported by the javascript used to render the html page. Including your own versions will work, but you will have to put these files in the same directory as the file you want to convert and this cannot  be required to lambda users. Depending on the way you refer/incude these files, you may also have to distribute them with your html file. I thinking on a way to enable user to specify custom names and environments to be merged to the main ones. 
- Third one is also related to modifications in the source code. The current converter was not intented to detect/use optional parameters for thm and thm-like environments. I just pushed a solution (look at/download/replace file `latex_envs.py`) but this will only work for the ipynb --> latex conversion. Support for optional parameters in the live notebook and html output will be added in the future, but I am quite busy for now. 

Closing this and keeping the label "enhancement" to remind me to work on support for optional parameters.
