### ISSUE TITLE
latex error when compiling documentation file

### ISSUE THREAD

**Issue by wiai** [jfbercher/jupyter_latex_envs#9]
Hi, 
I am trying to compile the documentation and get this error when running
"xelatex documentation.tex" like stated in "readme.md":

```
! You can't use `\spacefactor' in math mode.
\@->\spacefactor
                 \@m
l.36 ... \textbf{User \(\LaTeX\) definitions file}
                                                   \item
````
and more errors afterwards.
When specifying "xelatex -interaction=nonstopmode documentation.tex" like in the documentation, the pdf file seems to be produced correctly but latex still reports the list of errors. 

The relevant output:
[log.txt](https://github.com/jfbercher/jupyter_latex_envs/files/570964/log.txt)

Running Windows 10, Miktex 2.9.

Thanks!
wiai

**Comment by jfbercher** [comment]
hmmm...
ok, actually a small but interesting issue. It is related to the use of the `\LaTeX` macro. In order to have it interpreted by mathjax, we have to enclose it between dollars. It is converted as is when converting to latex. But this macro is a text mode macro, and thus latex complains that it is not uses as it should (but we must enclose it between $ in order to have it interpreted in the livenotebook or in html)...  
Thus for the moment I have introduced a simple substitution in the notebook --> latex conversion. 

More importantly, looking at the other errors, I realized that the processing of comments (any line beginning by a % is ignored) was not always correct. This was because the latex text is reflowed sometimes in a strange way during the markdown to latex conversion. I have introduced and pushed a fix for that. Anyway, one should have a look at the log file since the conversion may not be perfect (actually the text resulting for standard notebook -> latex conversion is also not always perfect)

Thanks for your comment!
